# see: https://github.com/EmbarkStudios/cargo-deny

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "Zlib"
]

[advisories]
yanked = "deny"
ignore = [
    "RUSTSEC-2024-0436"
]

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]