name: CI
on:
    push:
      branches:
        - main
      tags-ignore:
        - v*
      paths-ignore:
        - '**.md'
    pull_request:
      paths-ignore:
        - '**.md'

env:
  CARGO_INCREMENTAL: 0


jobs:
    setup:
        name: Set up Rust
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
        
          - name: Set up Rust toolchain
            uses: dtolnay/rust-toolchain@stable
            with:
              toolchain: stable
    
          - name: Install Clippy and Rustfmt
            run: |
              rustup component add clippy
              rustup component add rustfmt    

    dependencies:
        name: Run Deny
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: EmbarkStudios/cargo-deny-action@v2

    format:
        name: Run Rustfmt
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - uses: actions/checkout@v4
            - name: Run rustfmt
              run: cargo fmt -- --check
    lint:
        name: Run Clippy
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - uses: actions/checkout@v4
            - name: Run clippy
              run: cargo clippy -- -D warnings

