name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    timeout-minutes: 20
    outputs:
      gview_version: ${{ env.GVIEW_VERSION }}
    env:
      # For some builds, we use cross to test on 32-bit and big-endian systems.
      CARGO: cargo
      # When CARGO is set to CROSS, this is set to `--target matrix.target`.
      TARGET_FLAGS: ""
      # When CARGO is set to CROSS, TARGET_DIR includes matrix.target.
      TARGET_DIR: ./target
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        build: [linux, linux-arm, macos, win-msvc, win32-msvc]
        include:
        - build: linux
          os: ubuntu-24.04
          rust: stable
          target: x86_64-unknown-linux-musl
        - build: linux-arm
          os: ubuntu-24.04
          rust: stable
          target: arm-unknown-linux-gnueabihf
        - build: macos
          os: macos-latest
          rust: stable
          target: aarch64-apple-darwin
        - build: win-msvc
          os: windows-latest
          rust: stable
          target: x86_64-pc-windows-msvc
        - build: win32-msvc
          os: windows-latest
          rust: stable
          target: i686-pc-windows-msvc

    steps:
    - name: Get the release version from the tag
      shell: bash
      if: env.GVIEW_VERSION == ''
      run: |
        # Apparently, this is the right way to get a tag name. Really?
        #
        # See: https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32167/highlight/true#M1027
        echo "GVIEW_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        echo "version is: ${{ env.GVIEW_VERSION }}"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}

    - name: Install Linux dependencies
      if: matrix.build == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev pkg-config build-essential

    - name: Install ARM cross-compilation dependencies
      if: matrix.build == 'linux-arm'
      run: |
        sudo dpkg --add-architecture armhf
        sudo apt-get update
        sudo apt-get install -y libssl-dev:armhf pkg-config build-essential

    - name: Install macOS dependencies
      if: matrix.build == 'macos'
      run: |
        # ARM64 macOS uses Homebrew default path
        brew install openssl@3 pkg-config
        echo "OPENSSL_DIR=/opt/homebrew/opt/openssl@3" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/opt/homebrew/opt/openssl@3/lib/pkgconfig" >> $GITHUB_ENV

    - name: Use Cross
      if: matrix.build == 'linux-arm'
      shell: bash
      run: |
        cargo install cross
        echo "CARGO=cross" >> $GITHUB_ENV
        echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
        echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV

    - name: Show command used for Cargo
      run: |
        echo "cargo command is: ${{ env.CARGO }}"
        echo "target flag is: ${{ env.TARGET_FLAGS }}"
        echo "target dir is: ${{ env.TARGET_DIR }}"

    - name: Build release binary
      run: ${{ env.CARGO }} build --verbose --release ${{ env.TARGET_FLAGS }}
      env:
        # Force static linking for cross-compilation consistency
        OPENSSL_STATIC: 1

    - name: Strip release binary (linux and macos)
      if: matrix.build == 'linux' || matrix.build == 'macos'
      run: strip "target/${{ matrix.target }}/release/gview"

    - name: Strip release binary (arm)
      if: matrix.build == 'linux-arm'
      run: |
        docker run --rm -v \
          "$PWD/target:/target:Z" \
          rustembedded/cross:arm-unknown-linux-gnueabihf \
          arm-linux-gnueabihf-strip \
          /target/arm-unknown-linux-gnueabihf/release/gview

    - name: Build archive
      shell: bash
      run: |
        staging="gview-${{ env.GVIEW_VERSION }}-${{ matrix.target }}"
        mkdir -p "$staging"/{complete,doc}

        cp {README.md,LICENSE} "$staging/"

        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp "target/${{ matrix.target }}/release/gview.exe" "$staging/"
          7z a "$staging.zip" "$staging"
          echo "ASSET=$staging.zip" >> $GITHUB_ENV
        else
          # The man page is only generated on Unix systems. ¯\_(ツ)_/¯
          cp "target/${{ matrix.target }}/release/gview" "$staging/"
          tar czf "$staging.tar.gz" "$staging"
          echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
        fi

    - name: Publish
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ env.ASSET }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cargo-publish:
    name: Cargo publish
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: release
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-workspaces
        uses: dtolnay/rust-toolchain@stable
        with:
          crate: cargo-workspaces

      - name: Cargo publish
        run: |
          git config --global user.email "runner@gha.local"
          git config --global user.name "Github Action"
          cargo install cargo-workspaces
          cargo workspaces publish \
            --yes --force '*' --exact \
            --no-git-commit --allow-dirty --skip-published --token ${{ secrets.CRATES_IO_TOKEN }} \
            custom ${{ needs.release.outputs.GVIEW_VERSION }}